FROM nginx:alpine
FROM nginx:alpine
WORKDIR /app
COPY . .
COPY ./nginx.conf /etc/nginx/nginx.conf


#RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
#COPY content /usr/share/nginx/html
#COPY conf /etc/nginx
#VOLUME /usr/share/nginx/html
#VOLUME /etc/nginx