# referenced from:
# https://ashwin9798.medium.com/nginx-with-docker-and-node-js-a-beginners-guide-434fe1216b6b
version: "3.8"
services:
  node:
    restart: always
    build:
      context: ./app
    ports:
      - "8080:8080"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - node